MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
CONSOLE_ENABLE = no
ENCODER_ENABLE = yes
LTO_ENABLE = yes
OLED_ENABLE = yes
WPM_ENABLE = no

RGBLIGHT_ENABLE = yes

#RGB_MATRIX_ENABLE = yes
#RGB_MATRIX_DRIVER = ws2812
